### ISSUE TITLE
fitur form app

### ISSUE THREAD

**Issue by galihap76** [mizzcode/form-karyawan#1]
Bah, enyong olih kontribusi? go nambahi fitur login, registrasi, karo lupa password atik PHP. Tapi ngko, yen enyong bener bener lagi akeh waktu garap projekan program. Olih bah?

**Comment by mizzcode** [comment]
bebas gal🔥🔥

**Comment by galihap76** [comment]
> bebas gal🔥🔥

Ok sip bah.
